---
apiVersion: v1
kind: Pod
metadata:
    name: inventory-manager
    labels:
      app: inventory-manager
spec:
  containers:
  - name: routing
    image: chadminn/routing:latest
    imagePullPolicy: Always
    ports:
    - containerPort: 5000
  - name: webapp
    image: chadminn/webapp:latest
    imagePullPolicy: Always
    ports:
    - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: port-service
  labels:
    app: port-service 
spec:
  type: NodePort
  selector:
    app: inventory-manager
  ports:
  - name: http
    protocol: TCP
    targetPort: 8080
    port: 80
    nodePort: 30001
